version: '3.8'

services:
  web:
    image: python:3.10-slim
    container_name: flask_app
    volumes:
      - .:/app
      - ./instance:/app/instance
    working_dir: /app
    command: python run.py
    ports:
      - "80:80"